# Generated by Django 4.1.7 on 2023-04-14 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_content_alter_post_created_and_mare'),
        ('blog', '0002_alter_post_content_alter_post_created_and_more'),
    ]

    operations = [
    ]
