# Generated by Django 4.1.7 on 2023-04-14 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_merge_20230414_2129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
    ]
